version: '3.3'

services:
  app:
    container_name: tastetable-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/taste-table
      - API_URL=http://mongo
      - ACCESS_TOKEN_KEY=MyVeryVeryAccessTokenKey
      - ACCESS_TOKEN_TIME=15h
      - REFRESH_TOKEN_KEY=MyVeryVeryRefreshTokenKey
      - REFRESH_TOKEN_TIME=15d
      - REFRESH_TIME_MS=84600000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: tastetable-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
